# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wGU3uuWTe7by6d-YJVvw3CCC73Ij3TPN
"""

import cv2

for i in range(1, 6):
    rasm = cv2.imread(f"{i}.png")
    oqqora = cv2.cvtColor(rasm, cv2.COLOR_BGR2GRAY)
    cv2.imwrite(f"{i}_oqqora.png", oqqora)